import Vue from 'vue'
import { 
    Button, 
    Dialog, 
    Input, 
    Breadcrumb,
    BreadcrumbItem,
    Table,
    TableColumn,
    Pagination,
    Upload,
    Row,
    Col,
    Submenu,
    MenuItem,
    Menu,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Select,
    Option,
    DatePicker,
    Tabs,
    TabPane,
    Form,
    FormItem,
    Cascader,
    CheckboxGroup,
    Checkbox
 } from 'element-ui'
//  import '@/assets/scss/element-variables.scss'

 Vue.use(Button)
 Vue.use(Dialog)
 Vue.use(Input)
 Vue.use(Breadcrumb)
 Vue.use(BreadcrumbItem)
 Vue.use(Table)
 Vue.use(TableColumn)
 Vue.use(Pagination)
 Vue.use(Upload)
 Vue.use(Row)
 Vue.use(Col)
 Vue.use(Submenu)
 Vue.use(MenuItem)
 Vue.use(Menu)
 Vue.use(Dropdown)
 Vue.use(DropdownMenu)
 Vue.use(DropdownItem)
 Vue.use(Select)
 Vue.use(Option)
 Vue.use(DatePicker)
 Vue.use(Tabs)
 Vue.use(TabPane)
 Vue.use(Form)
 Vue.use(FormItem)
 Vue.use(Cascader)
 Vue.use(CheckboxGroup)
 Vue.use(Checkbox)
